use_frameworks!
platform :ios, '13.0'

target 'TheQKit_Example' do
  pod 'TheQKit'
#  pod 'TheQKit', :path => '../'
  pod 'MBProgressHUD'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FirebaseUI/Phone'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

end







