use_frameworks!
platform :ios, '10.0'

target 'TheQKit_Example' do
  pod 'TheQKit'
  #pod 'TheQKit', :path => '../'
  pod 'MBProgressHUD'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FirebaseUI/Phone'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

end

pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            # Ensure 32 bit symbols aren't included when building
            config.build_settings['ARCHS'] = '$(ARCHS_STANDARD_64_BIT)'
            
        end
        
    end
end




